// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChWsQQvby8NF8ylePFbmi5SLjRqfSSDtU',
    appId: '1:719803741783:web:aed31b9f1d355d380d9512',
    messagingSenderId: '719803741783',
    projectId: 'ecommerce-app-2213d',
    authDomain: 'ecommerce-app-2213d.firebaseapp.com',
    databaseURL: 'https://ecommerce-app-2213d-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerce-app-2213d.appspot.com',
    measurementId: 'G-8DYNZX50JM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2ixcSUAX9O3fTXeiVgP1Uy5zD9c66NS8',
    appId: '1:719803741783:android:a5b993aa6bacbe9a0d9512',
    messagingSenderId: '719803741783',
    projectId: 'ecommerce-app-2213d',
    databaseURL: 'https://ecommerce-app-2213d-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerce-app-2213d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1jEu4mfbJZuUHxVF0slLTc02bndJzfjI',
    appId: '1:719803741783:ios:4d52602222cb856f0d9512',
    messagingSenderId: '719803741783',
    projectId: 'ecommerce-app-2213d',
    databaseURL: 'https://ecommerce-app-2213d-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerce-app-2213d.appspot.com',
    iosClientId: '719803741783-85n94dlv8d2ap9ktcpdd1htdj9cgmgvf.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1jEu4mfbJZuUHxVF0slLTc02bndJzfjI',
    appId: '1:719803741783:ios:4d52602222cb856f0d9512',
    messagingSenderId: '719803741783',
    projectId: 'ecommerce-app-2213d',
    databaseURL: 'https://ecommerce-app-2213d-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerce-app-2213d.appspot.com',
    iosClientId: '719803741783-85n94dlv8d2ap9ktcpdd1htdj9cgmgvf.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );
}
